name: tw
version: 0.0.8
description: "Flutter UI with Tailwind style."
homepage: https://github.com/denyocr93
repository: https://github.com/denyocr93
issue_tracker: https://github.com/denyocr93
environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.5.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
